name: Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_indepth: yes
