name: Metrics

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      # ✅ Only install jq, Docker is pre-installed on GitHub-hosted runners
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # ✅ Run metrics using your Personal Access Token (GH_PAT)
      - name: Generate GitHub metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}
          filename: github-metrics.svg
          base: header, activity
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_indepth: yes
