name: Metrics

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io jq

      - name: Generate GitHub metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}
          filename: github-metrics.svg
          base: header, activity
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_indepth: yes
