name: Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      # ✅ Install jq and Docker (safely)
      - name: Install Docker and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      # ✅ Generate metrics using PAT
      - name: Generate GitHub metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}
          filename: github-metrics.svg
          base: header, activity
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_indepth: yes
