name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]  # every hour
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "activity"
          config_timezone: "Asia/Kolkata"
